version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
        - teste 
    depends_on:
      - sql-database
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-database;Database=4Tables;User=sa;Password=59I^3w#HF#tI;TrustServerCertificate=true

  sql-database:
    container_name: sql-database
    image: mcr.microsoft.com/mssql/server:2022-latest
    pull_policy: if_not_present
    networks:
        - teste
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '59I^3w#HF#tI'
    ports:
      - '1433:1433'
    expose:
      - '1433'

volumes:
  sqlserver-data:
     driver: local

networks:
  teste:
    driver: bridge



